name: Actions Workflow

on: 
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  push:
  pull_request: 
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Git Data
        run: |
          #GITHUB_SHA --> Commit ID of the specific commit that triggred this workflow
          echo $GITHUB_SHA 
          #GITHUB_REPOSITORY --> User Name and Repository Name
          echo $GITHUB_REPOSITORY
          #GITHUB_WORKSPACE --> Workspace directory same as default pwd
          echo $GITHUB_WORKSPACE
          #github --> Context object that contains data related to github
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'master'
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Update file
        id: file-update
        run: |
          echo "This line is added by ${{ github.job }} JOB in ${{ github.workflow }} WORKFLOW" >> README.md
      - name: Save state
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Amitnick # defaults to "github-actions[bot]"
          commit_user_email: amitnikumbh54@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com" 
          commit_message: Apply automatic changes
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Log commit_hash
        run: echo "${{ steps.commit.outputs.commit_hash }}"